[package]
name = "netps-trojan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
netps-core.workspace = true
thiserror = "1.0.50"
